name = "Individual Command Cycler"
version = 1
copyright = "Nope but feel free to let me know what you have in mind, maybe we can make it v2 instead"
description = [[Give individual orders quickly without selecting each unit/command manually. Use for reclaiming/scouting in multiple directions, TML-barrages, spreading ground-fire etc.]]
author = "FreadyFish"
url = ""
uid = "individual-command-cycler-v1"
icon = "/mods/IndividualCommandCycler/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = { }
before = {}
after = {}
