name = "Individual Command Cycler"
version = 1
copyright = ""
description = [[Forked from Group Scatter v4 by 4z0t]]
author = "FreadyFish"
url = ""
uid = "Individual-Command-Cycler-FF-v1"
icon = "/mods/IndividualCommandCycler/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = { }
before = {}
after = {}
