name = "Select Air Scouts"
uid = "1889abc8-8cd4-11eb-9045-9bac37550f0f"
version = 1
description = "Adds a hotkey to select all air intelligence planes"
author = "SkepticSpecter"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }
