name = "FilterSelection FF"
uid = "Filter-Selection-v1-FF"
version = 1
copyright = ""
description = "Forked from FilterSelection v1 by 4z0t"
author = "FreadyFish"
url = ""
icon = '/mods/FilterSelection/icon.jpg'
enabled = true
exclusive = false
ui_only = true
conflicts = { "a91e97de-51e2-11eb-ae93-0242ac130006" }
