name = "Idle Engies&Factories Keybinding"
version = 2
copyright = "Dragun123@2020"
description = "HotKey For Idle Engies&Factories. Also adds hotkey for choosing nearest t2 engies and t3 engies. Created with help from Charin"
author = "Dragun123"
uid = "6defa425-09d7-498f-8c44-a05d4b8985x2"
selectable = true
icon = "/mods/HotKeyIdleEngie&Factories/IdleEngi&Factory.png"
enabled = true
exclusive = false
ui_only = true
requires = {}
conflicts = {}
before = {}
after = {}