name = "Zoom Acceleration"
uid = "Zoom-Acceleration-v1"
version = 1
description = "Allows you to set the acceleration factors for zooming, in the gameplay options tab."
author = "odomobo"
url = "https://bitbucket.org/odomobo/zoom-acceleration-mod"
selectable = true
enabled = true
exclusive = false
ui_only = true
