name = "Strategic Defence Range Preview"
author = "Katawunga"
version = 10.0
uid = "22e7d17c-ba99-11ed-afa1-0242ac100010"
description = "This mod erases the need to check the ranges of the enemy SMDs (or TMDs) with a capable builder before firing a missile.\nIt does this by showing the range of SMDs and TMDs around the mouse cursor while an SML or TML is selected by holding the shift key. \nFor a TML, two circles are drawn: A smaller one for the Aeon TMD and a bigger one for the other factions.\nThis mod also shows a dynamic line from the unitlocation to the current mouselocation, indicating the flight path of the missile for further guidance.\nPressing spacebar while having an SML selected will create a static ring for the range of an SMD at the current mouse location and clicking control will remove all of these static circles."
icon = "/mods/StrategicDefenceRangePreview/icon/no_antinuke5.png"
url = ""
copyright = "Free"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}