name = "Selection Lock"
version = 1
copyright = ""
description = "Prevents selection of assisting units. You can still select one at a time. Can configure to limit by unit type. Based on Selection Lock v4"
author = "FreadyFish"
url = ""
uid = "selection-lock-ff-v1"
exclusive = false
ui_only =true
conflicts = {}
