name = "Additional Orders Extension"
version = 1
copyright = ""
description = [[Forked from Additional Orders Extension v5 by 4z0t. Requires UI Mod Tools V8]]
author = "FreadyFish"
url = ""
uid = "additional-orders-extension-v05"
exclusive = false
ui_only = true
conflicts = {}
