name = "EconomyTools"
uid = "Auto-Pause-FF-v1"
version = 1
copyright = ""
description = "Forked from Economy Tools FA v2 by AdmiralZeech, and extracted only auto-pause function."
author = "FreadyFish"
url = ""
icon = "/mods/EconomyTools/mod_icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = { }
requiresNames = { }
conflicts = { "2B033CD1-AD77-4A90-A319-11080A399535" }
before = { }
after = { }
