name = "UI-Party Essentials"
version = 1
copyright = ""
description = "UI-Party reduced to essentials"
author = "FreadyFish"
url = ""
uid = "starting-options-freadyfish-v01"
exclusive = false
ui_only = true
conflicts = {  }
requires = {"zcbf6277-24e3-437a-b968-Common-v1"}
before = {"zcbf6277-24e3-437a-b968-Common-v1"}
after = { }
