name = "Starting Options (from UIP)"
version = 1
copyright = ""
description = "Starting options from UI-Party only, to reduce problems with other code."
author = ""
url = ""
uid = "starting-options-freadyfish-v01"
exclusive = false
ui_only = true
conflicts = {  }
requires = {"zcbf6277-24e3-437a-b968-Common-v1"}
before = {"zcbf6277-24e3-437a-b968-Common-v1"}
after = { }
