name = "UI-Party"
version = 1
copyright = ""
description = "UI-Party reduced to functional essentials"
author = "FreadyFish"
url = ""
uid = "UI-Party-v1-FF"
exclusive = false
ui_only = true
conflicts = {  }
requires = {"Common-Mod-Tools-v1-FF"}
before = {"Common-Mod-Tools-v1-FF"}
after = { }
