name = "MultiHotkeys"
version = 1
copyright = ""
description = [[Smart hotkeys with multiple purposes in different situations. Forked from Additional Orders Extension v5 by 4z0t. Requires UI Mod Tools V8]]
author = "FreadyFish"
url = ""
uid = "Multi-Hotkeys-FF-v1"
exclusive = false
ui_only = true
conflicts = {}
