name = "Advanced Hotkeys"
uid = "Advanced-Hotkeys-FF-v1"
version = 1
description = "Expands hotkey menu with context specific commands and key combos. Includes a variety of useful commands."
author = "FreadyFish"
exclusive = false
ui_only = true
after = { "ui-mod-tools-4z0t-v12-FF", "Common-Mod-Tools-v1-FF" }
icon = "/mods/AdvancedHotkeys/icon.png"