name = "Disable Zoom In For Groups"
version = 4
copyright = ""
description = "Allows you to configure the zoom level that double tapping a ctrl group locks to. Requires UI Mod Tools by 4z0t, thnks to him for letting me use his tools!"
author = "SpikeyNoob"
url = ""
uid = "Disable-Zoom-In-For-Groups-v4"
icon = "/mods/DisableZoomInForGroups/icon.png"
exclusive = false
selectable = true
enabled = true
ui_only = true
conflicts = {}