name = "Command Cycler"
version = 1
copyright = ""
description = [[Forked from Group Scatter v4 by 4z0t]]
author = "FreadyFish"
url = ""
uid = "Command-Cycler-v1-FF"
icon = "/mods/CommandCycler/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = { }
before = {}
after = {}
