name = "Extra mini map"
version = 3
copyright = "Eternal-"
description = "New look of mini-map. No borders"
icon = "/mods/Extra mini map/logo.png"
author = "Eternal-"
url = ""
uid = "Extra-Mini-Map-v3"
exclusive = false
ui_only = true
conflicts = {}
