name = "Unit Overlays"
uid = "Unit-Overlays-FF-v1"
version = 1
copyright = ""
description = [[Forked from Idle Engineers Light v10 by 4z0t. Requires UI mod tools and UI mod loader]]
author = "FreadyFish"
url = ""
icon = "/mods/UnitOverlays/icon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {"ui-mod-loader-v02"}
requiresNames = {}
conflicts = {"idle-engineers-light-v10"}
before = {}
after = {}
__umt = true