keyOrder = {
	'Esc',
	'Shift-Esc',
	'Ctrl-Esc',
	'Ctrl-Shift-Esc',
	'Alt-Esc',
	'Shift-Alt-Esc',
	'Ctrl-Alt-Esc',
	'Ctrl-Alt-Shift-Esc',

	'F1',
	'Shift-F1',
	'Ctrl-F1',
	'Ctrl-Shift-F1',
	'Alt-F1',
	'Shift-Alt-F1',
	'Ctrl-Alt-F1',
	'Ctrl-Alt-Shift-F1',

	'F2',
	'Shift-F2',
	'Ctrl-F2',
	'Ctrl-Shift-F2',
	'Alt-F2',
	'Shift-Alt-F2',
	'Ctrl-Alt-F2',
	'Ctrl-Alt-Shift-F2',

	'F3',
	'Shift-F3',
	'Ctrl-F3',
	'Ctrl-Shift-F3',
	'Alt-F3',
	'Shift-Alt-F3',
	'Ctrl-Alt-F3',
	'Ctrl-Alt-Shift-F3',

	'F4',
	'Shift-F4',
	'Ctrl-F4',
	'Ctrl-Shift-F4',
	'Alt-F4',
	'Shift-Alt-F4',
	'Ctrl-Alt-F4',
	'Ctrl-Alt-Shift-F4',

	'F5',
	'Shift-F5',
	'Ctrl-F5',
	'Ctrl-Shift-F5',
	'Alt-F5',
	'Shift-Alt-F5',
	'Ctrl-Alt-F5',
	'Ctrl-Alt-Shift-F5',

	'F6',
	'Shift-F6',
	'Ctrl-F6',
	'Ctrl-Shift-F6',
	'Alt-F6',
	'Shift-Alt-F6',
	'Ctrl-Alt-F6',
	'Ctrl-Alt-Shift-F6',

	'F7',
	'Shift-F7',
	'Ctrl-F7',
	'Ctrl-Shift-F7',
	'Alt-F7',
	'Shift-Alt-F7',
	'Ctrl-Alt-F7',
	'Ctrl-Alt-Shift-F7',

	'F8',
	'Shift-F8',
	'Ctrl-F8',
	'Ctrl-Shift-F8',
	'Alt-F8',
	'Shift-Alt-F8',
	'Ctrl-Alt-F8',
	'Ctrl-Alt-Shift-F8',

	'F9',
	'Shift-F9',
	'Ctrl-F9',
	'Ctrl-Shift-F9',
	'Alt-F9',
	'Shift-Alt-F9',
	'Ctrl-Alt-F9',
	'Ctrl-Alt-Shift-F9',

	'F10',
	'Shift-F10',
	'Ctrl-F10',
	'Ctrl-Shift-F10',
	'Alt-F10',
	'Shift-Alt-F10',
	'Ctrl-Alt-F10',
	'Ctrl-Alt-Shift-F10',

	'F11',
	'Shift-F11',
	'Ctrl-F11',
	'Ctrl-Shift-F11',
	'Alt-F11',
	'Shift-Alt-F11',
	'Ctrl-Alt-F11',
	'Ctrl-Alt-Shift-F11',

	'F12',
	'Shift-F12',
	'Ctrl-F12',
	'Ctrl-Shift-F12',
	'Alt-F12',
	'Shift-Alt-F12',
	'Ctrl-Alt-F12',
	'Ctrl-Alt-Shift-F12',

	'Tilde',
	'Shift-Tilde',
	'Ctrl-Tilde',
	'Ctrl-Shift-Tilde',
	'Alt-Tilde',
	'Shift-Alt-Tilde',
	'Ctrl-Alt-Tilde',
	'Ctrl-Alt-Shift-Tilde',

	'Backquote',
	'Shift-Backquote',
	'Ctrl-Backquote',
	'Ctrl-Shift-Backquote',
	'Alt-Backquote',
	'Shift-Alt-Backquote',
	'Ctrl-Alt-Backquote',
	'Ctrl-Alt-Shift-Backquote',

	'1',
	'Shift-1',
	'Ctrl-1',
	'Ctrl-Shift-1',
	'Alt-1',
	'Shift-Alt-1',
	'Ctrl-Alt-1',
	'Ctrl-Alt-Shift-1',

	'2',
	'Shift-2',
	'Ctrl-2',
	'Ctrl-Shift-2',
	'Alt-2',
	'Shift-Alt-2',
	'Ctrl-Alt-2',
	'Ctrl-Alt-Shift-2',

	'3',
	'Shift-3',
	'Ctrl-3',
	'Ctrl-Shift-3',
	'Alt-3',
	'Shift-Alt-3',
	'Ctrl-Alt-3',
	'Ctrl-Alt-Shift-3',

	'4',
	'Shift-4',
	'Ctrl-4',
	'Ctrl-Shift-4',
	'Alt-4',
	'Shift-Alt-4',
	'Ctrl-Alt-4',
	'Ctrl-Alt-Shift-4',

	'5',
	'Shift-5',
	'Ctrl-5',
	'Ctrl-Shift-5',
	'Alt-5',
	'Shift-Alt-5',
	'Ctrl-Alt-5',
	'Ctrl-Alt-Shift-5',

	'6',
	'Shift-6',
	'Ctrl-6',
	'Ctrl-Shift-6',
	'Alt-6',
	'Shift-Alt-6',
	'Ctrl-Alt-6',
	'Ctrl-Alt-Shift-6',

	'7',
	'Shift-7',
	'Ctrl-7',
	'Ctrl-Shift-7',
	'Alt-7',
	'Shift-Alt-7',
	'Ctrl-Alt-7',
	'Ctrl-Alt-Shift-7',

	'8',
	'Shift-8',
	'Ctrl-8',
	'Ctrl-Shift-8',
	'Alt-8',
	'Shift-Alt-8',
	'Ctrl-Alt-8',
	'Ctrl-Alt-Shift-8',

	'9',
	'Shift-9',
	'Ctrl-9',
	'Ctrl-Shift-9',
	'Alt-9',
	'Shift-Alt-9',
	'Ctrl-Alt-9',
	'Ctrl-Alt-Shift-9',

	'0',
	'Shift-0',
	'Ctrl-0',
	'Ctrl-Shift-0',
	'Alt-0',
	'Shift-Alt-0',
	'Ctrl-Alt-0',
	'Ctrl-Alt-Shift-0',

	'Minus',
	'Shift-Minus',
	'Ctrl-Minus',
	'Ctrl-Shift-Minus',
	'Alt-Minus',
	'Shift-Alt-Minus',
	'Ctrl-Alt-Minus',
	'Ctrl-Alt-Shift-Minus',

	'Equals',
	'Shift-Equals',
	'Ctrl-Equals',
	'Ctrl-Shift-Equals',
	'Alt-Equals',
	'Shift-Alt-Equals',
	'Ctrl-Alt-Equals',
	'Ctrl-Alt-Shift-Equals',

	'Backspace',
	'Shift-Backspace',
	'Ctrl-Backspace',
	'Ctrl-Shift-Backspace',
	'Alt-Backspace',
	'Shift-Alt-Backspace',
	'Ctrl-Alt-Backspace',
	'Ctrl-Alt-Shift-Backspace',

	'Tab',
	'Shift-Tab',
	'Ctrl-Tab',
	'Ctrl-Shift-Tab',
	'Alt-Tab',
	'Shift-Alt-Tab',
	'Ctrl-Alt-Tab',
	'Ctrl-Alt-Shift-Tab',

	'Q',
	'Shift-Q',
	'Ctrl-Q',
	'Ctrl-Shift-Q',
	'Alt-Q',
	'Shift-Alt-Q',
	'Ctrl-Alt-Q',
	'Ctrl-Alt-Shift-Q',

	'W',
	'Shift-W',
	'Ctrl-W',
	'Ctrl-Shift-W',
	'Alt-W',
	'Shift-Alt-W',
	'Ctrl-Alt-W',
	'Ctrl-Alt-Shift-W',

	'E',
	'Shift-E',
	'Ctrl-E',
	'Ctrl-Shift-E',
	'Alt-E',
	'Shift-Alt-E',
	'Ctrl-Alt-E',
	'Ctrl-Alt-Shift-E',

	'R',
	'Shift-R',
	'Ctrl-R',
	'Ctrl-Shift-R',
	'Alt-R',
	'Shift-Alt-R',
	'Ctrl-Alt-R',
	'Ctrl-Alt-Shift-R',

	'T',
	'Shift-T',
	'Ctrl-T',
	'Ctrl-Shift-T',
	'Alt-T',
	'Shift-Alt-T',
	'Ctrl-Alt-T',
	'Ctrl-Alt-Shift-T',

	'Y',
	'Shift-Y',
	'Ctrl-Y',
	'Ctrl-Shift-Y',
	'Alt-Y',
	'Shift-Alt-Y',
	'Ctrl-Alt-Y',
	'Ctrl-Alt-Shift-Y',

	'U',
	'Shift-U',
	'Ctrl-U',
	'Ctrl-Shift-U',
	'Alt-U',
	'Shift-Alt-U',
	'Ctrl-Alt-U',
	'Ctrl-Alt-Shift-U',

	'I',
	'Shift-I',
	'Ctrl-I',
	'Ctrl-Shift-I',
	'Alt-I',
	'Shift-Alt-I',
	'Ctrl-Alt-I',
	'Ctrl-Alt-Shift-I',

	'O',
	'Shift-O',
	'Ctrl-O',
	'Ctrl-Shift-O',
	'Alt-O',
	'Shift-Alt-O',
	'Ctrl-Alt-O',
	'Ctrl-Alt-Shift-O',

	'P',
	'Shift-P',
	'Ctrl-P',
	'Ctrl-Shift-P',
	'Alt-P',
	'Shift-Alt-P',
	'Ctrl-Alt-P',
	'Ctrl-Alt-Shift-P',

	'LeftBracket',
	'Shift-LeftBracket',
	'Ctrl-LeftBracket',
	'Ctrl-Shift-LeftBracket',
	'Alt-LeftBracket',
	'Shift-Alt-LeftBracket',
	'Ctrl-Alt-LeftBracket',
	'Ctrl-Alt-Shift-LeftBracket',

	'RightBracket',
	'Shift-RightBracket',
	'Ctrl-RightBracket',
	'Ctrl-Shift-RightBracket',
	'Alt-RightBracket',
	'Shift-Alt-RightBracket',
	'Ctrl-Alt-RightBracket',
	'Ctrl-Alt-Shift-RightBracket',

	'Backslash',
	'Shift-Backslash',
	'Ctrl-Backslash',
	'Ctrl-Shift-Backslash',
	'Alt-Backslash',
	'Shift-Alt-Backslash',
	'Ctrl-Alt-Backslash',
	'Ctrl-Alt-Shift-Backslash',

	'CapsLock',
	'Shift-CapsLock',
	'Ctrl-CapsLock',
	'Ctrl-Shift-CapsLock',
	'Alt-CapsLock',
	'Shift-Alt-CapsLock',
	'Ctrl-Alt-CapsLock',
	'Ctrl-Alt-Shift-CapsLock',

	'A',
	'Shift-A',
	'Ctrl-A',
	'Ctrl-Shift-A',
	'Alt-A',
	'Shift-Alt-A',
	'Ctrl-Alt-A',
	'Ctrl-Alt-Shift-A',

	'S',
	'Shift-S',
	'Ctrl-S',
	'Ctrl-Shift-S',
	'Alt-S',
	'Shift-Alt-S',
	'Ctrl-Alt-S',
	'Ctrl-Alt-Shift-S',

	'D',
	'Shift-D',
	'Ctrl-D',
	'Ctrl-Shift-D',
	'Alt-D',
	'Shift-Alt-D',
	'Ctrl-Alt-D',
	'Ctrl-Alt-Shift-D',

	'F',
	'Shift-F',
	'Ctrl-F',
	'Ctrl-Shift-F',
	'Alt-F',
	'Shift-Alt-F',
	'Ctrl-Alt-F',
	'Ctrl-Alt-Shift-F',

	'G',
	'Shift-G',
	'Ctrl-G',
	'Ctrl-Shift-G',
	'Alt-G',
	'Shift-Alt-G',
	'Ctrl-Alt-G',
	'Ctrl-Alt-Shift-G',

	'H',
	'Shift-H',
	'Ctrl-H',
	'Ctrl-Shift-H',
	'Alt-H',
	'Shift-Alt-H',
	'Ctrl-Alt-H',
	'Ctrl-Alt-Shift-H',

	'J',
	'Shift-J',
	'Ctrl-J',
	'Ctrl-Shift-J',
	'Alt-J',
	'Shift-Alt-J',
	'Ctrl-Alt-J',
	'Ctrl-Alt-Shift-J',

	'K',
	'Shift-K',
	'Ctrl-K',
	'Ctrl-Shift-K',
	'Alt-K',
	'Shift-Alt-K',
	'Ctrl-Alt-K',
	'Ctrl-Alt-Shift-K',

	'L',
	'Shift-L',
	'Ctrl-L',
	'Ctrl-Shift-L',
	'Alt-L',
	'Shift-Alt-L',
	'Ctrl-Alt-L',
	'Ctrl-Alt-Shift-L',

	'Semicolon',
	'Shift-Semicolon',
	'Ctrl-Semicolon',
	'Ctrl-Shift-Semicolon',
	'Alt-Semicolon',
	'Shift-Alt-Semicolon',
	'Ctrl-Alt-Semicolon',
	'Ctrl-Alt-Shift-Semicolon',

	'Quote',
	'Shift-Quote',
	'Ctrl-Quote',
	'Ctrl-Shift-Quote',
	'Alt-Quote',
	'Shift-Alt-Quote',
	'Ctrl-Alt-Quote',
	'Ctrl-Alt-Shift-Quote',

	'Enter',
	'Shift-Enter',
	'Ctrl-Enter',
	'Ctrl-Shift-Enter',
	'Alt-Enter',
	'Shift-Alt-Enter',
	'Ctrl-Alt-Enter',
	'Ctrl-Alt-Shift-Enter',

	'Z',
	'Shift-Z',
	'Ctrl-Z',
	'Ctrl-Shift-Z',
	'Alt-Z',
	'Shift-Alt-Z',
	'Ctrl-Alt-Z',
	'Ctrl-Alt-Shift-Z',

	'X',
	'Shift-X',
	'Ctrl-X',
	'Ctrl-Shift-X',
	'Alt-X',
	'Shift-Alt-X',
	'Ctrl-Alt-X',
	'Ctrl-Alt-Shift-X',

	'C',
	'Shift-C',
	'Ctrl-C',
	'Ctrl-Shift-C',
	'Alt-C',
	'Shift-Alt-C',
	'Ctrl-Alt-C',
	'Ctrl-Alt-Shift-C',

	'V',
	'Shift-V',
	'Ctrl-V',
	'Ctrl-Shift-V',
	'Alt-V',
	'Shift-Alt-V',
	'Ctrl-Alt-V',
	'Ctrl-Alt-Shift-V',

	'B',
	'Shift-B',
	'Ctrl-B',
	'Ctrl-Shift-B',
	'Alt-B',
	'Shift-Alt-B',
	'Ctrl-Alt-B',
	'Ctrl-Alt-Shift-B',

	'N',
	'Shift-N',
	'Ctrl-N',
	'Ctrl-Shift-N',
	'Alt-N',
	'Shift-Alt-N',
	'Ctrl-Alt-N',
	'Ctrl-Alt-Shift-N',

	'M',
	'Shift-M',
	'Ctrl-M',
	'Ctrl-Shift-M',
	'Alt-M',
	'Shift-Alt-M',
	'Ctrl-Alt-M',
	'Ctrl-Alt-Shift-M',

	'Comma',
	'Shift-Comma',
	'Ctrl-Comma',
	'Ctrl-Shift-Comma',
	'Alt-Comma',
	'Shift-Alt-Comma',
	'Ctrl-Alt-Comma',
	'Ctrl-Alt-Shift-Comma',

	'Period',
	'Shift-Period',
	'Ctrl-Period',
	'Ctrl-Shift-Period',
	'Alt-Period',
	'Shift-Alt-Period',
	'Ctrl-Alt-Period',
	'Ctrl-Alt-Shift-Period',

	'Slash',
	'Shift-Slash',
	'Ctrl-Slash',
	'Ctrl-Shift-Slash',
	'Alt-Slash',
	'Shift-Alt-Slash',
	'Ctrl-Alt-Slash',
	'Ctrl-Alt-Shift-Slash',

	'Space',
	'Shift-Space',
	'Ctrl-Space',
	'Ctrl-Shift-Space',
	'Alt-Space',
	'Shift-Alt-Space',
	'Ctrl-Alt-Space',
	'Ctrl-Alt-Shift-Space',

	'Insert',
	'Shift-Insert',
	'Ctrl-Insert',
	'Ctrl-Shift-Insert',
	'Alt-Insert',
	'Shift-Alt-Insert',
	'Ctrl-Alt-Insert',
	'Ctrl-Alt-Shift-Insert',

	'Home',
	'Shift-Home',
	'Ctrl-Home',
	'Ctrl-Shift-Home',
	'Alt-Home',
	'Shift-Alt-Home',
	'Ctrl-Alt-Home',
	'Ctrl-Alt-Shift-Home',

	'Pause',
	'Shift-Pause',
	'Ctrl-Pause',
	'Ctrl-Shift-Pause',
	'Alt-Pause',
	'Shift-Alt-Pause',
	'Ctrl-Alt-Pause',
	'Ctrl-Alt-Shift-Pause',

	'PageUp',
	'Shift-PageUp',
	'Ctrl-PageUp',
	'Ctrl-Shift-PageUp',
	'Alt-PageUp',
	'Shift-Alt-PageUp',
	'Ctrl-Alt-PageUp',
	'Ctrl-Alt-Shift-PageUp',

	'Delete',
	'Shift-Delete',
	'Ctrl-Delete',
	'Ctrl-Shift-Delete',
	'Alt-Delete',
	'Shift-Alt-Delete',
	'Ctrl-Alt-Delete',
	'Ctrl-Alt-Shift-Delete',

	'End',
	'Shift-End',
	'Ctrl-End',
	'Ctrl-Shift-End',
	'Alt-End',
	'Shift-Alt-End',
	'Ctrl-Alt-End',
	'Ctrl-Alt-Shift-End',

	'PageDown',
	'Shift-PageDown',
	'Ctrl-PageDown',
	'Ctrl-Shift-PageDown',
	'Alt-PageDown',
	'Shift-Alt-PageDown',
	'Ctrl-Alt-PageDown',
	'Ctrl-Alt-Shift-PageDown',

	'UpArrow',
	'Shift-UpArrow',
	'Ctrl-UpArrow',
	'Ctrl-Shift-UpArrow',
	'Alt-UpArrow',
	'Shift-Alt-UpArrow',
	'Ctrl-Alt-UpArrow',
	'Ctrl-Alt-Shift-UpArrow',

	'LeftArrow',
	'Shift-LeftArrow',
	'Ctrl-LeftArrow',
	'Ctrl-Shift-LeftArrow',
	'Alt-LeftArrow',
	'Shift-Alt-LeftArrow',
	'Ctrl-Alt-LeftArrow',
	'Ctrl-Alt-Shift-LeftArrow',

	'DownArrow',
	'Shift-DownArrow',
	'Ctrl-DownArrow',
	'Ctrl-Shift-DownArrow',
	'Alt-DownArrow',
	'Shift-Alt-DownArrow',
	'Ctrl-Alt-DownArrow',
	'Ctrl-Alt-Shift-DownArrow',

	'RightArrow',
	'Shift-RightArrow',
	'Ctrl-RightArrow',
	'Ctrl-Shift-RightArrow',
	'Alt-RightArrow',
	'Shift-Alt-RightArrow',
	'Ctrl-Alt-RightArrow',
	'Ctrl-Alt-Shift-RightArrow',

	'Num0',
	'Shift-Num0',
	'Ctrl-Num0',
	'Ctrl-Shift-Num0',
	'Alt-Num0',
	'Shift-Alt-Num0',
	'Ctrl-Alt-Num0',
	'Ctrl-Alt-Shift-Num0',

	'Num1',
	'Shift-Num1',
	'Ctrl-Num1',
	'Ctrl-Shift-Num1',
	'Alt-Num1',
	'Shift-Alt-Num1',
	'Ctrl-Alt-Num1',
	'Ctrl-Alt-Shift-Num1',

	'Num2',
	'Shift-Num2',
	'Ctrl-Num2',
	'Ctrl-Shift-Num2',
	'Alt-Num2',
	'Shift-Alt-Num2',
	'Ctrl-Alt-Num2',
	'Ctrl-Alt-Shift-Num2',

	'Num3',
	'Shift-Num3',
	'Ctrl-Num3',
	'Ctrl-Shift-Num3',
	'Alt-Num3',
	'Shift-Alt-Num3',
	'Ctrl-Alt-Num3',
	'Ctrl-Alt-Shift-Num3',

	'Num4',
	'Shift-Num4',
	'Ctrl-Num4',
	'Ctrl-Shift-Num4',
	'Alt-Num4',
	'Shift-Alt-Num4',
	'Ctrl-Alt-Num4',
	'Ctrl-Alt-Shift-Num4',

	'Num5',
	'Shift-Num5',
	'Ctrl-Num5',
	'Ctrl-Shift-Num5',
	'Alt-Num5',
	'Shift-Alt-Num5',
	'Ctrl-Alt-Num5',
	'Ctrl-Alt-Shift-Num5',

	'Num6',
	'Shift-Num6',
	'Ctrl-Num6',
	'Ctrl-Shift-Num6',
	'Alt-Num6',
	'Shift-Alt-Num6',
	'Ctrl-Alt-Num6',
	'Ctrl-Alt-Shift-Num6',

	'Num7',
	'Shift-Num7',
	'Ctrl-Num7',
	'Ctrl-Shift-Num7',
	'Alt-Num7',
	'Shift-Alt-Num7',
	'Ctrl-Alt-Num7',
	'Ctrl-Alt-Shift-Num7',

	'Num8',
	'Shift-Num8',
	'Ctrl-Num8',
	'Ctrl-Shift-Num8',
	'Alt-Num8',
	'Shift-Alt-Num8',
	'Ctrl-Alt-Num8',
	'Ctrl-Alt-Shift-Num8',

	'Num9',
	'Shift-Num9',
	'Ctrl-Num9',
	'Ctrl-Shift-Num9',
	'Alt-Num9',
	'Shift-Alt-Num9',
	'Ctrl-Alt-Num9',
	'Ctrl-Alt-Shift-Num9',

	'NumLock',
	'Shift-NumLock',
	'Ctrl-NumLock',
	'Ctrl-Shift-NumLock',
	'Alt-NumLock',
	'Shift-Alt-NumLock',
	'Ctrl-Alt-NumLock',
	'Ctrl-Alt-Shift-NumLock',

	'NumSlash',
	'Shift-NumSlash',
	'Ctrl-NumSlash',
	'Ctrl-Shift-NumSlash',
	'Alt-NumSlash',
	'Shift-Alt-NumSlash',
	'Ctrl-Alt-NumSlash',
	'Ctrl-Alt-Shift-NumSlash',

	'NumStar',
	'Shift-NumStar',
	'Ctrl-NumStar',
	'Ctrl-Shift-NumStar',
	'Alt-NumStar',
	'Shift-Alt-NumStar',
	'Ctrl-Alt-NumStar',
	'Ctrl-Alt-Shift-NumStar',

	'NumMinus',
	'Shift-NumMinus',
	'Ctrl-NumMinus',
	'Ctrl-Shift-NumMinus',
	'Alt-NumMinus',
	'Shift-Alt-NumMinus',
	'Ctrl-Alt-NumMinus',
	'Ctrl-Alt-Shift-NumMinus',

	'NumPlus',
	'Shift-NumPlus',
	'Ctrl-NumPlus',
	'Ctrl-Shift-NumPlus',
	'Alt-NumPlus',
	'Shift-Alt-NumPlus',
	'Ctrl-Alt-NumPlus',
	'Ctrl-Alt-Shift-NumPlus',

	'NumEnter',
	'Shift-NumEnter',
	'Ctrl-NumEnter',
	'Ctrl-Shift-NumEnter',
	'Alt-NumEnter',
	'Shift-Alt-NumEnter',
	'Ctrl-Alt-NumEnter',
	'Ctrl-Alt-Shift-NumEnter',

	'NumDecimal',
	'Shift-NumDecimal',
	'Ctrl-NumDecimal',
	'Ctrl-Shift-NumDecimal',
	'Alt-NumDecimal',
	'Shift-Alt-NumDecimal',
	'Ctrl-Alt-NumDecimal',
	'Ctrl-Alt-Shift-NumDecimal',
}
