name = "4z0t's ScoreBoard Tweaked"
version = 1
copyright = ""
description = [[Forked from 4z0t's ScoreBoard v8]]
author = "FreadyFish"
url = ""
icon = "/mods/4SB/icon.png"
uid = "4z0ts-Scoreboard-v1-FF"
exclusive = false
ui_only = true
conflicts = {"4z0ts-scoreboard-v8"}
