name = "Reveal Positions (legal)"
version = 3
copyright = "Myxir"
description = "Reveals starting locations of players. Invicible button, faction icon with army color. Doesn't reveal players on random maps, only start locations."
author = "Myxir, Eternal-, Nomander"
url = ""
uid = "c6aed627-6285-446f-b52c-111886c381dc"
exclusive = false
ui_only = true
conflicts = {}
icon = "/mods/Reveal Positions/logo.png"