name = "ZeP_MiniMapZoom"
uid = "Mini-Map-Zoom-v2"
version = 2
copyright = ""
description = "Disabling minimap when zoomed out"
author = "Ze_PilOt"
url = ""
icon = "/mods/ZeP_MiniMapZoom/minimapmodicon.png"
selectable = true
enabled = true
exclusive = false
ui_only = true
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}