name = "Advanced Target Priorities"
version = 1
copyright = ""
description = "Forked from ATP v1.1"
author = "FreadyFish"
url = ""
uid = "Advanced-Target-Priorities-FF-v1"
exclusive = false
ui_only = true
conflicts = {}
